![title](https://68.media.tumblr.com/853cf21e477e27168d3e62a792b8b592/tumblr_ooxp609mbo1uqdbpso1_400.gif)

### Messi vs Ronaldo

### Fonte: https://data.world/makeovermonday/2020w15-messi-vs-ronaldo-stats
### https://www.ogol.com.br/home.php

### La Liga

#### Gols por temporada
#### Assistências por temporada
#### Jogos por temporada
#### Média de gols por jogos
#### Média de gols por minuto jogado


### Champions

#### Gols por temporada
#### Assistências por temporada
#### Jogos por temporada
#### Média de gols por jogos
#### Média de gols por minuto jogado

### Importando as bibliotecas necessárias

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Importando a base de dados para o nosso projeto

Os dados abaixo de referem às informações

In [2]:
#Base de dados completa, com os gols de Messi e Ronaldo entre as temporadas 2009-2010 e 2017-2018

df_messironaldo = pd.read_excel('data/MessiRonaldo.xlsx')

In [3]:
df_messironaldo

,Season,Player,Liga_Goals,Liga_Asts,Liga_Aps,Liga_Mins,Liga_Team_Goals,CL_Goals,CL_Asts,CL_Aps,CL_Mins,CL_Team_Goals
0,2017-18,Messi,34,12,36,2996,99,6,2,10,783,17
1,2017-18,Ronaldo,26,5,27,2297,94,15,3,13,1170,33
2,2016-17,Messi,37,9,34,2832,116,11,2,9,810,26
3,2016-17,Ronaldo,25,6,29,2544,106,12,5,13,1200,36
4,2015-16,Messi,26,16,33,2729,112,6,1,7,630,22
5,2015-16,Ronaldo,35,11,36,3184,110,16,4,12,1109,28
6,2014-15,Messi,43,21,38,3375,110,10,6,13,1145,31
7,2014-15,Ronaldo,48,16,35,3096,118,10,4,12,1064,24
8,2013-14,Messi,28,12,31,2498,100,8,1,7,630,21
9,2013-14,Ronaldo,31,11,30,2537,104,17,6,11,991,41
10,2012-13,Messi,46,14,32,2629,115,8,3,11,827,18
11,2012-13,Ronaldo,34,11,34,2716,103,12,1,12,1080,26
12,2011-12,Messi,50,20,37,3270,114,14,9,11,990,35
13,2011-12,Ronaldo,46,13,38,3353,121,10,4,10,930,35
14,2010-11,Messi,31,21,33,2862,95,12,4,13,1050,30
15,2010-11,Ronaldo,40,13,34,2914,102,6,4,12,1018,25
16,2009-10,Messi,34,13,35,2841,98,8,0,11,985,20
17,2009-10,Ronaldo,26,11,29,2462,102,7,2,6,450,16

In [ ]:
#Dados dos gols de Lionel Messi

df_messi = df_messironaldo.query('Player == "Messi"')

In [ ]:
#Dados dos gols de Cristiano Ronaldo

df_ronaldo = df_messironaldo.query('Player == "Ronaldo"')

### La Liga

Comparação entre os dois levando apenas em consideração os gols em La Liga

![](https://cdn.clipart.email/aa04921fb81612f5c87869e0872191da_la-liga-pes-2020-leagues-competitions-pro-evolution-soccer-_256-256.png)

### Champions League

Comparação entre os dois levando apenas em consideração os gols na Champions League

![](https://logospng.org/download/uefa-champions-league/logo-uefa-champions-league-256.png)